const products = [
    {
        name: "Cordless Drill",
        description: "A powerful cordless drill with multiple speed settings.",
        price: 49.99,
        category: "Tools",
        images: ["https://imgur.com/sn4ofDi.jpg"],
        seller: "Tool Depot",
        location: "New York, NY",
        availability: "3 weeks",
        renting: {
            hours: 4.99,
            days: 14.99,
            weeks: 49.99,
            months: 149.99,
        },
    },
    {
        name: "Circular Saw",
        description: "High-performance circular saw for precise cutting.",
        price: 89.99,
        category: "Tools",
        images: ["https://imgur.com/sn4ofDi.jpg"],
        seller: "Precision Tools",
        location: "Los Angeles, CA",
        availability: "1 month",
        renting: {
            hours: 7.99,
            days: 19.99,
            weeks: 69.99,
            months: 199.99,
        },
    },
    {
        name: "Hammer",
        description: "Durable claw hammer for all your construction needs.",
        price: 14.99,
        category: "Tools",
        images:["https://imgur.com/sn4ofDi.jpg"],
        seller: "Builders Hub",
        location: "Chicago, IL",
        availability: "9 months",
        renting: {
            hours: 1.99,
            days: 4.99,
            weeks: 14.99,
            months: 39.99,
        },
    },
    {
        name: "Wrench Set",
        description: "A set of 10 wrenches in various sizes.",
        price: 29.99,
        category: "Tools",
        images:["https://imgur.com/sn4ofDi.jpg"],
        seller: "Garage Essentials",
        location: "Houston, TX",
        availability: "2 weeks",
        renting: {
            hours: 2.99,
            days: 8.99,
            weeks: 24.99,
            months: 59.99,
        },
    },
    {
        name: "Acoustic Guitar",
        description: "Full-size acoustic guitar with rich sound and wooden finish.",
        price: 119.99,
        category: "Music",
        images: ["https://imgur.com/sn4ofDi.jpg"],
        seller: "String Masters",
        location: "Austin, TX",
        availability: "2 months",
        renting: {
            hours: 3.99,
            days: 11.99,
            weeks: 34.99,
            months: 89.99,
        },
    },
    {
        name: "Bluetooth Speaker",
        description: "Portable waterproof Bluetooth speaker with deep bass.",
        price: 59.99,
        category: "Electronics",
        images: ["https://imgur.com/sn4ofDi.jpg"],
        seller: "SoundGrid",
        location: "San Diego, CA",
        availability: "1 week",
        renting: {
            hours: 2.49,
            days: 6.99,
            weeks: 18.99,
            months: 54.99,
        },
    },
    {
        name: "Mountain Bike",
        description: "Durable mountain bike suitable for all terrains.",
        price: 349.99,
        category: "Transport",
        images: ["https://imgur.com/sn4ofDi.jpg"],
        seller: "CyclePro",
        location: "Denver, CO",
        availability: "6 months",
        renting: {
            hours: 9.99,
            days: 24.99,
            weeks: 99.99,
            months: 249.99,
        },
    },
    {
        name: "Halloween Costume",
        description: "Spooky vampire costume for adults with accessories.",
        price: 39.99,
        category: "Costume",
        images:["https://imgur.com/sn4ofDi.jpg"],
        seller: "PartyZone",
        location: "Las Vegas, NV",
        availability: "5 days",
        renting: {
            hours: 1.99,
            days: 5.99,
            weeks: 14.99,
            months: 29.99,
        },
    },
    {
        name: "Fiction Book Set",
        description: "Set of 5 popular fiction novels.",
        price: 24.99,
        category: "Books",
        images: ["https://imgur.com/sn4ofDi.jpg"],
        seller: "BookNest",
        location: "Portland, OR",
        availability: "3 months",
        renting: {
            hours: 0.99,
            days: 2.99,
            weeks: 9.99,
            months: 24.99,
        },
    },
    {
        name: "NVIDIA RTX 3080 GPU",
        description: "High-end graphics card for gaming and rendering.",
        price: 699.99,
        category: "Electronics",
        images: ["https://imgur.com/sn4ofDi.jpg"],
        seller: "TechCore",
        location: "Seattle, WA",
        availability: "2 months",
        renting: {
            hours: 15.99,
            days: 44.99,
            weeks: 129.99,
            months: 299.99,
        },
    },
    {
        name: "Gaming Laptop",
        description: "Powerful gaming laptop with RTX graphics and SSD storage.",
        price: 1299.99,
        category: "Electronics",
        images:["https://imgur.com/sn4ofDi.jpg"],
        seller: "Gamer's Hub",
        location: "Miami, FL",
        availability: "4 months",
        renting: {
            hours: 12.99,
            days: 39.99,
            weeks: 109.99,
            months: 269.99,
        },
    },
    {
        name: "PlayStation 5 Console",
        description: "Next-gen PlayStation console with DualSense controller.",
        price: 499.99,
        category: "Gaming",
        images: ["https://imgur.com/sn4ofDi.jpg"],
        seller: "Console World",
        location: "Phoenix, AZ",
        availability: "3 weeks",
        renting: {
            hours: 8.99,
            days: 22.99,
            weeks: 79.99,
            months: 189.99,
        },
    },
];

module.exports = products;